import type { CourseCategory } from "./course-offerings";
import { finalizeResourcesForSite } from "./resource-ingestion";
import { supplementalHubResources } from "./resource-supplements";

export interface Course {
  id: string;
  title: string;
  subtitle: string;
  category: CourseCategory;
  categoryLabel: string;
  price: string;
  duration: string;
  schedule: string;
  description: string;
  featured: boolean;
  syllabus: string[];
  curriculum: {
    title: string;
    topics: string[];
  }[];
  outcomes: string[];
}

/** Public vault categories (marketing `/resources`). */
export type ResourceHubCategory =
  | "general-notes"
  | "topicals"
  | "yearly-past-papers"
  | "examiner-reports"
  | "examiner-guides"
  | "checklists"
  | "quick-worksheets"
  | "vocabulary"
  | "solved-papers"
  | "featured";

/** Sub-type for vault items in `general-notes` and `vocabulary` (optional; inferred when omitted). */
export type ResourceNotesSubCategory =
  | "summary-writing"
  | "comprehension"
  | "essay-writing"
  | "directed-writing"
  | "grammar"
  | "solved-papers"
  | "comprehension-vocabulary"
  | "essay-vocabulary"
  | "general-vocabulary"
  | "directed-writing-vocabulary"
  | "summary-writing-vocabulary"
  | "p2-50-words"
  | "checklists";

export interface Resource {
  id: string;
  title: string;
  category: ResourceHubCategory;
  subject: string;
  level: string;
  paper: string;
  year: string;
  section?: string;
  /** Hosted PDF or document URL; replace with your CDN or `/public` paths. */
  fileUrl: string;
  description: string;
  subCategory?: ResourceNotesSubCategory;
  /** When `"mcq"`, the resource view renders an interactive MCQ quiz instead of a PDF iframe. */
  type?: "mcq";
}

/** Notes hub topic tiles / filters (`general-notes` only; vocabulary uses its own lists in the UI). */
export const NOTES_HUB_SUBTOPICS: { id: ResourceNotesSubCategory; label: string }[] = [
  { id: "summary-writing", label: "Summary Writing" },
  { id: "comprehension", label: "Comprehension" },
  { id: "essay-writing", label: "Essay Writing" },
  { id: "directed-writing", label: "Directed Writing" },
  { id: "grammar", label: "Grammar" },
];

/** Paper 1 Topicals hub sections only (no overlap with Paper 2). */
export const TOPICALS_PAPER_1_SECTION_DEFS = [
  { id: "comprehension", label: "Comprehension" },
  { id: "summary", label: "Summary" },
] as const;

export const TOPICALS_PAPER_1_ALWAYS_SECTION_LABELS: readonly string[] =
  TOPICALS_PAPER_1_SECTION_DEFS.map((s) => s.label);

/** Paper 2 Topicals hub sections only (no overlap with Paper 1). */
export const TOPICALS_PAPER_2_SECTION_DEFS = [
  { id: "essay", label: "Essay" },
  { id: "directed-writing", label: "Directed Writing" },
] as const;

export const TOPICALS_PAPER_2_ALWAYS_SECTION_LABELS: readonly string[] =
  TOPICALS_PAPER_2_SECTION_DEFS.map((s) => s.label);

export const RESOURCE_HUB_CATEGORIES: {
  id: ResourceHubCategory;
  label: string;
  blurb: string;
}[] = [
  {
    id: "general-notes",
    label: "Notes",
    blurb: "Topic-based notes to build writing, reading, and grammar foundations.",
  },
  {
    id: "topicals",
    label: "Topicals",
    blurb: "Section-based practice packs grouped by paper and skill.",
  },
  {
    id: "yearly-past-papers",
    label: "Yearlies",
    blurb: "Official papers and inserts, cleaned up for quick session-based practice.",
  },
  {
    id: "examiner-reports",
    label: "Scripts",
    blurb: "Real student scripts with examiner-style feedback and examples.",
  },
  {
    id: "examiner-guides",
    label: "Examiner Guides",
    blurb: "Examiner reports and Examiner Candidate Responses (ECR) — what gains and loses marks.",
  },
  {
    id: "checklists",
    label: "Marking Schemes",
    blurb: "Solutions and mark schemes grouped by paper, then by section or session.",
  },
  {
    id: "quick-worksheets",
    label: "Quick Worksheets",
    blurb: "Interactive MCQ assessments and PDF checklists with instant scoring and explanations.",
  },
  {
    id: "vocabulary",
    label: "Vocabulary",
    blurb: "Targeted vocabulary lists and banks for comprehension, essay writing, and general use.",
  },
  {
    id: "solved-papers",
    label: "Solved Papers",
    blurb: "Model answers and worked papers to guide your exam preparation.",
  },
];

/**
 * The four real offerings surfaced on `/courses` (see `COURSE_CATEGORY_SLUGS_OFFERED`):
 *   1. O Level English Language — 1123          (`o-level-english-1123`)
 *   2. IGCSE English as a Second Language 0510/0511 (`igcse-esl-0510-0511`)
 *   3. IGCSE English as a First Language — 0500 (`igcse-fle-0500`)
 *   4. AS Level English Language — 9093         (`a-level-english-9093`)
 * `english-literature` / `creative-writing-workshop` remain as legacy data but are
 * filtered out of the public directory.
 *
 * TODO (Task 2 — syllabus PDFs): the Cambridge syllabus PDFs are not yet hosted.
 * The "View syllabus" card link points at the in-app syllabus/curriculum page (text),
 * so nothing is broken. When the syllabus PDFs are supplied, host them on Supabase
 * (do NOT commit PDFs to the repo) and add a download link per course.
 */
export const courses: Course[] = [
  {
    id: "o-level-english-1123",
    title: "O Level English Language",
    subtitle: "CAIE 1123 - Complete Preparation",
    category: "o-level",
    categoryLabel: "O Level",
    price: "PKR 25,000",
    duration: "4 Months",
    schedule: "3 sessions/week",
    description:
      "A structured, rubric-driven programme for Cambridge O Level English Language (1123). We build repeatable exam thinking through targeted practice on directed writing, composition, and comprehension.",
    featured: true,
    syllabus: [
      "Paper 1: Directed Writing & Composition",
      "Paper 2: Comprehension & Summary",
      "Examiner-aligned marking practice",
      "Timed mock examinations",
    ],
    curriculum: [
      {
        title: "Foundation: Reading & Analysis",
        topics: [
          "Comprehension strategies for unseen passages",
          "Inference and implication techniques",
          "Summary writing: precision under word limits",
          "Vocabulary building through context",
        ],
      },
      {
        title: "Directed Writing Mastery",
        topics: [
          "Understanding task requirements and audience",
          "Letter, report, speech, and article formats",
          "Tone adaptation and register control",
          "Examiner expectation alignment",
        ],
      },
      {
        title: "Composition & Creative Expression",
        topics: [
          "Narrative structure and pacing",
          "Descriptive writing: sensory detail and control",
          "Argumentative essay construction",
          "Discursive writing with balanced perspective",
        ],
      },
      {
        title: "Exam Strategy & Timed Practice",
        topics: [
          "Time allocation per question",
          "Common deduction patterns and how to avoid them",
          "Full paper mock under exam conditions",
          "Personalised feedback and improvement plans",
        ],
      },
    ],
    outcomes: [
      "Write with clarity and structure under timed conditions",
      "Identify and apply examiner marking criteria",
      "Produce directed writing that hits every assessment objective",
      "Develop a repeatable approach to comprehension and summary",
      "Build confidence through consistent, measurable progress",
    ],
  },
  {
    id: "igcse-esl-0510-0511",
    title: "IGCSE English as a Second Language",
    subtitle: "CAIE 0510 / 0511 - Complete Preparation",
    category: "igcse",
    categoryLabel: "IGCSE",
    price: "PKR 25,000",
    duration: "4 Months",
    schedule: "3 sessions/week",
    description:
      "A structured programme for Cambridge IGCSE English as a Second Language (0510 / 0511). We build reading, writing, listening, and speaking skills with rubric-aligned practice and checked work.",
    featured: true,
    syllabus: [
      "Paper 1: Reading & Writing",
      "Paper 2: Listening",
      "Speaking endorsement (0511)",
      "Exam-aligned marking practice",
    ],
    curriculum: [
      {
        title: "Reading Skills",
        topics: [
          "Skimming, scanning, and locating detail",
          "Note-making and information transfer",
          "Understanding tone, purpose, and audience",
          "Multiple-matching and gap-fill techniques",
        ],
      },
      {
        title: "Writing Skills",
        topics: [
          "Emails, letters, reports, and articles",
          "Register and audience adaptation",
          "Summary writing within word limits",
          "Accuracy: grammar, spelling, and punctuation",
        ],
      },
      {
        title: "Listening Skills",
        topics: [
          "Listening for gist and specific detail",
          "Note completion and multiple choice",
          "Following conversations and monologues",
          "Timed practice under exam conditions",
        ],
      },
      {
        title: "Speaking (0511)",
        topics: [
          "Conversation and topic development",
          "Fluency, range, and accuracy",
          "Handling follow-up questions confidently",
          "Mock speaking tests with feedback",
        ],
      },
    ],
    outcomes: [
      "Read and respond to a range of text types with confidence",
      "Write clearly for different audiences and purposes",
      "Answer listening tasks accurately under timed conditions",
      "Communicate fluently in the speaking assessment (0511)",
      "Apply examiner marking criteria across all papers",
    ],
  },
  {
    id: "igcse-fle-0500",
    title: "IGCSE English as a First Language",
    subtitle: "CAIE 0500 - Complete Preparation",
    category: "igcse",
    categoryLabel: "IGCSE",
    price: "PKR 27,000",
    duration: "4 Months",
    schedule: "3 sessions/week",
    description:
      "A structured programme for Cambridge IGCSE English as a First Language (0500). We develop close reading, directed writing, and composition skills through examiner-aligned practice and feedback.",
    featured: true,
    syllabus: [
      "Paper 1: Reading",
      "Paper 2: Directed Writing & Composition",
      "Coursework / Speaking component",
      "Exam-aligned marking practice",
    ],
    curriculum: [
      {
        title: "Reading & Analysis",
        topics: [
          "Comprehension of explicit and implicit meaning",
          "Analysing language and writer's effect",
          "Summary writing with precision",
          "Selecting and synthesising information",
        ],
      },
      {
        title: "Directed Writing",
        topics: [
          "Responding to reading material",
          "Form, audience, and purpose control",
          "Evaluating ideas and arguments",
          "Structuring a clear, developed response",
        ],
      },
      {
        title: "Composition",
        topics: [
          "Descriptive writing: detail and atmosphere",
          "Narrative writing: structure and pacing",
          "Crafting accurate, varied sentences",
          "Planning under timed conditions",
        ],
      },
      {
        title: "Exam Strategy",
        topics: [
          "Time allocation per question",
          "Common deduction patterns and how to avoid them",
          "Full paper mock under exam conditions",
          "Personalised feedback and improvement plans",
        ],
      },
    ],
    outcomes: [
      "Read critically and analyse a writer's craft",
      "Produce directed writing that meets every assessment objective",
      "Write vivid descriptive and narrative compositions",
      "Summarise and synthesise with accuracy",
      "Achieve top-band marks through rubric-aligned practice",
    ],
  },
  {
    id: "a-level-english-9093",
    title: "AS/A Level English Language",
    subtitle: "CAIE 9093 - Advanced Programme",
    category: "a-level",
    categoryLabel: "A Level",
    price: "PKR 35,000",
    duration: "6 Months",
    schedule: "3 sessions/week",
    description:
      "An advanced programme for AS and A Level English Language (9093). We develop sophisticated analytical writing, commentary skills, and language awareness required for top-band performance.",
    featured: true,
    syllabus: [
      "Paper 1: Reading (Passages & Commentary)",
      "Paper 2: Writing (Directed & Composition)",
      "Paper 3: Text Analysis (A2)",
      "Paper 4: Language Topics (A2)",
    ],
    curriculum: [
      {
        title: "Textual Analysis & Commentary",
        topics: [
          "Linguistic framework for text analysis",
          "Audience, purpose, and context identification",
          "Stylistic feature recognition and effect analysis",
          "Commentary writing: structure and depth",
        ],
      },
      {
        title: "Advanced Directed Writing",
        topics: [
          "Complex audience adaptation",
          "Persuasive and rhetorical technique mastery",
          "Voice, register, and genre conventions",
          "Synthesis of source material into original writing",
        ],
      },
      {
        title: "Language in Context (A2)",
        topics: [
          "English as a global language: debates and perspectives",
          "Language and the self: identity and representation",
          "Language change: historical and contemporary",
          "Child language acquisition theories",
        ],
      },
      {
        title: "Examination Technique",
        topics: [
          "Band descriptor analysis for each paper",
          "Planning under pressure: structured approaches",
          "Full mock examinations with examiner-style feedback",
          "Targeted improvement based on diagnostic review",
        ],
      },
    ],
    outcomes: [
      "Analyse texts with precision using linguistic frameworks",
      "Write directed responses that demonstrate genre mastery",
      "Construct well-evidenced arguments on language topics",
      "Navigate A2 papers with confidence and critical depth",
      "Achieve top-band marks through deliberate, rubric-aligned practice",
    ],
  },
  {
    id: "english-literature",
    title: "English Literature",
    subtitle: "Poetry, Prose & Drama",
    category: "literature",
    categoryLabel: "Literature",
    price: "PKR 30,000",
    duration: "5 Months",
    schedule: "2 sessions/week",
    description:
      "Deep engagement with set texts, poetry, and drama. We develop critical reading, close analysis, and essay writing skills that go beyond surface-level interpretation.",
    featured: false,
    syllabus: [
      "Set text study: prose and drama",
      "Unseen poetry analysis",
      "Comparative essay techniques",
      "Contextual understanding and critical perspectives",
    ],
    curriculum: [
      {
        title: "Prose Study",
        topics: [
          "Character analysis and development",
          "Narrative voice and structural choices",
          "Thematic exploration across texts",
          "Contextual reading and critical lenses",
        ],
      },
      {
        title: "Drama Study",
        topics: [
          "Dramatic conventions and stagecraft",
          "Dialogue analysis and subtext",
          "Conflict, tension, and resolution",
          "Performance-aware close reading",
        ],
      },
      {
        title: "Poetry & Unseen Analysis",
        topics: [
          "Poetic form, metre, and sound",
          "Imagery, symbolism, and figurative language",
          "Unseen poetry: structured approach",
          "Comparative poetry essays",
        ],
      },
      {
        title: "Essay Craft",
        topics: [
          "Thesis development and argument structure",
          "Embedding quotations with analytical commentary",
          "Exam-style essay planning and execution",
          "Peer review and refinement",
        ],
      },
    ],
    outcomes: [
      "Produce sophisticated literary analysis essays",
      "Engage critically with set texts and unseen poetry",
      "Develop original interpretations supported by close reading",
      "Write with confidence under exam conditions",
      "Appreciate literature as a lens for understanding the world",
    ],
  },
  {
    id: "creative-writing-workshop",
    title: "Creative Writing Workshop",
    subtitle: "Voice, Craft & Expression",
    category: "creative-writing",
    categoryLabel: "Creative Writing",
    price: "PKR 15,000",
    duration: "6 Weeks",
    schedule: "1 session/week",
    description:
      "A focused workshop for students who want to strengthen their creative voice. Ideal for composition prep, personal statements, and developing writing as a lifelong skill.",
    featured: true,
    syllabus: [
      "Narrative and descriptive writing techniques",
      "Voice development and style",
      "Workshop-based peer feedback",
      "Portfolio development",
    ],
    curriculum: [
      {
        title: "Finding Your Voice",
        topics: [
          "Reading as a writer: analysing craft choices",
          "Point of view and narrative distance",
          "Developing a distinctive writing style",
          "Writing prompts and daily practice habits",
        ],
      },
      {
        title: "Craft & Technique",
        topics: [
          "Show, don't tell: sensory writing",
          "Dialogue that reveals character",
          "Pacing and structure in short fiction",
          "Editing and revision strategies",
        ],
      },
      {
        title: "Workshop & Portfolio",
        topics: [
          "Peer workshop sessions with guided feedback",
          "Responding to critique constructively",
          "Compiling a polished writing portfolio",
          "Connecting creative writing to exam composition",
        ],
      },
    ],
    outcomes: [
      "Develop a confident, distinctive writing voice",
      "Apply narrative and descriptive techniques with precision",
      "Give and receive constructive feedback effectively",
      "Build a portfolio of polished creative work",
      "Transfer creative skills to exam composition tasks",
    ],
  },
];

const resourceLibrary: Resource[] = [
  {
    id: "1123-s24-insert-11",
    title: "May/June 2024 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "May/June 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s24-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s24-ms-11",
    title: "May/June 2024 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s24-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s24-ms-12",
    title: "May/June 2024 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s24-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s24-ms-21",
    title: "May/June 2024 — mark scheme (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "May/June 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s24-ms-21.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-insert-11-alt",
    title: "May/June 2025 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-insert-11-alt.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s25-insert-12",
    title: "May/June 2025 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s25-ms-11",
    title: "May/June 2025 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-ms-12",
    title: "May/June 2025 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-qp-11",
    title: "May/June 2025 — question paper (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-qp-11.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-12",
    title: "May/June 2025 — question paper (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-qp-12.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-21",
    title: "May/June 2025 — question paper (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-qp-21.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-22",
    title: "May/June 2025 — question paper (Paper 2 (variant 22))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 22)",
    year: "May/June 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-s25-qp-22.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-specimen-answers-paper-1",
    title: "Specimen — answers (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-answers-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-answers-paper-2",
    title: "Specimen — answers (Paper 2)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-answers-paper-2.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-insert-paper-1",
    title: "Specimen — insert (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-insert-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-ms-paper-1",
    title: "Specimen — mark scheme (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-ms-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-qp-paper-1",
    title: "Specimen — question paper (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-qp-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-qp-paper-2",
    title: "Specimen — question paper (Paper 2)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Specimen",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-specimen-qp-paper-2.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-w24-insert-11",
    title: "Nov 2024 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w24-insert-12",
    title: "Nov 2024 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w24-ms-11",
    title: "Nov 2024 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w24-ms-12",
    title: "Nov 2024 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w24-qp-11",
    title: "Nov 2024 — question paper (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-qp-11.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-12",
    title: "Nov 2024 — question paper (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-qp-12.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-21",
    title: "Nov 2024 — question paper (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-qp-21.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-22",
    title: "Nov 2024 — question paper (Paper 2 (variant 22))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 22)",
    year: "Nov 2024",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w24-qp-22.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w25-insert-11",
    title: "Nov 2025 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Nov 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w25-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w25-insert-12",
    title: "Nov 2025 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "Nov 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w25-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w25-ms-11",
    title: "Nov 2025 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w25-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w25-ms-12",
    title: "Nov 2025 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w25-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w25-ms-21",
    title: "Nov 2025 — mark scheme (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "Nov 2025",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/1123-w25-ms-21.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "changes-in-the-syllabus-1123",
    title: "Syllabus changes — 1123 overview",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/changes-in-the-syllabus-1123.pdf",
    description: "What changed in the latest syllabus cycle and how it affects classroom prep.",
  },
  {
    id: "complete-vocabulary-list-1123",
    title: "Complete vocabulary list (1123)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/complete-vocabulary-list-1123.pdf",
    description: "A wide-ranging vocabulary bank to support precision and range in writing tasks.",
  },
  {
    id: "o-level-1123-syllabus",
    title: "O Level English 1123 — syllabus (full)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/o-level-1123-syllabus.pdf",
    description: "CAIE syllabus document: aims, content, and assessment objectives.",
  },
  {
    id: "olevel-directed-writing-all-formats-notes",
    title: "Directed writing — all formats (notes)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/olevel-directed-writing-all-formats-notes.pdf",
    description: "Layouts and moves for common directed writing formats on Paper 1.",
  },
  {
    id: "olevel-directed-writing-formats-1123-notes",
    title: "Directed writing formats — 1123",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/olevel-directed-writing-formats-1123-notes.pdf",
    description: "Format expectations and structure reminders aligned to examiner criteria.",
  },
  {
    id: "olevel-directed-writing-text-wise-evaluation-notes",
    title: "Directed writing — text-wise evaluation",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/olevel-directed-writing-text-wise-evaluation-notes.pdf",
    description: "How to evaluate prompts closely and shape a task-sharp response.",
  },
  {
    id: "syllabus-1123-specification",
    title: "1123 specification — compact reference",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/syllabus-1123-specification.pdf",
    description: "A tighter syllabus reference for quick orientation before mocks.",
  },
  {
    id: "vocabulary-companion-1123",
    title: "Vocabulary companion pack",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/vocabulary-companion-1123.pdf",
    description: "Curated vocabulary support for O Level English responses.",
  },
  {
    id: "descriptive-essay",
    title: "Descriptive essay",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/descriptive-essay.pdf",
    description: "Notes and examples for controlled descriptive writing in Paper 1.",
  },
  {
    id: "narrative-essay",
    title: "Narrative essay",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/narrative-essay.pdf",
    description: "Narrative writing notes focused on plot control, pacing, and clarity.",
  },
  {
    id: "sample-essay-writing",
    title: "Sample essay writing",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/sample-essay-writing.pdf",
    description: "Sample essay notes to model structure, development, and language choices.",
  },
  {
    id: "final-vocabulary-for-essay-writing",
    title: "Final vocabulary for essay writing",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/final-vocabulary-for-essay-writing.pdf",
    description: "Essay-writing vocabulary support for stronger precision and range.",
  },
  {
    id: "directed-writing-notes",
    title: "Directed writing notes",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/directed-writing-notes.pdf",
    description: "Core directed-writing notes for task fit, register, and structure.",
  },
  {
    id: "pde-explained",
    title: "PDE explained",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/notes/pde-explained.pdf",
    description: "Breakdown of the PDE approach for sharper directed-writing responses.",
  },
  {
    id: "pde-format",
    title: "PDE format",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/pde-format.pdf",
    description: "Format guide for planning and organising PDE-style responses.",
  },
  {
    id: "part-b-short-response",
    title: "Part B short response",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/part-b-short-response.pdf",
    description: "Short-response guidance for concise, mark-aware Paper 1 answers.",
  },
  {
    id: "common-grammatical-errors-worksheet",
    title: "Common grammatical errors worksheet",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/notes/common-grammatical-errors-worksheet.pdf",
    description: "Grammar notes and drills on the error patterns students most often miss.",
  },
  {
    id: "grammar-3",
    title: "Grammar",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/notes/grammar-3.pdf",
    description: "General grammar support notes for cleaner exam writing.",
  },
  {
    id: "sentence-structures-worksheet",
    title: "Sentence structures worksheet",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/notes/sentence-structures-worksheet.pdf",
    description: "Sentence-structure practice to improve accuracy and control.",
  },
  {
    id: "punctuation-worksheet-3",
    title: "Punctuation worksheet",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/notes/punctuation-worksheet-3.pdf",
    description: "Punctuation practice focused on errors that commonly cost marks.",
  },
  {
    id: "worksheet-26-march-vocab-test-ms-marking-scheme",
    title: "Vocabulary marking scheme — test ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-26-march-vocab-test-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-exam-hack-4",
    title: "Exam hack — set 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Practice",
    fileUrl: "/resources/worksheet-exam-hack-4.pdf",
    description: "Short drill pack for reading and writing exam technique.",
  },
  {
    id: "worksheet-exam-hack-writers-effect",
    title: "Exam hack — writer's effect",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Practice",
    fileUrl: "/resources/worksheet-exam-hack-writers-effect.pdf",
    description: "Targeted practice on identifying and explaining writer’s effect.",
  },
  {
    id: "worksheet-interviewer-question-practice",
    title: "Interviewer question practice set",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-interviewer-question-practice.pdf",
    description: "Practice responding to interviewer-style prompts with clarity and control.",
  },
  {
    id: "worksheet-phrases-to-utilize",
    title: "Phrases to utilise",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-phrases-to-utilize.pdf",
    description: "High-utility phrases you can adapt across directed tasks.",
  },
  {
    id: "worksheet-pop-quiz",
    title: "Pop quiz — quick recall",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-pop-quiz.pdf",
    description: "Rapid checks to surface gaps before you attempt full papers.",
  },
  {
    id: "worksheet-sentences-you-can-use",
    title: "Sentences you can use",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-sentences-you-can-use.pdf",
    description: "Sentence patterns to improve cohesion, tone, and control.",
  },
  {
    id: "worksheet-tip-of-the-day-01",
    title: "Tip of the day — card 01",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-01.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-02",
    title: "Tip of the day — card 02",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-02.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-03",
    title: "Tip of the day — card 03",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-03.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-04",
    title: "Tip of the day — card 04",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-04.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-05",
    title: "Tip of the day — card 05",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-05.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-06",
    title: "Tip of the day — card 06",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-06.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-vocab-test-1-qp",
    title: "Vocabulary question paper — test 1",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-1-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-10-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 10",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-10-qp",
    title: "Vocabulary question paper — test 10",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-10-ws",
    title: "Vocabulary worksheet — test 10",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-11-qp",
    title: "Vocabulary question paper — test 11",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-11-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-11-ws",
    title: "Vocabulary worksheet — test 11",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-11-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-12-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 12",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-12-qp",
    title: "Vocabulary question paper — test 12",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-12-ws",
    title: "Vocabulary worksheet — test 12",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-13-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 13",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-13-qp",
    title: "Vocabulary question paper — test 13",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-13-ws",
    title: "Vocabulary worksheet — test 13",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-14-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 14",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-14-qp",
    title: "Vocabulary question paper — test 14",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-14-ws",
    title: "Vocabulary worksheet — test 14",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-2-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 2",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-2-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-3-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 3",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-3-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-3-qp",
    title: "Vocabulary question paper — test 3",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-3-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-4-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-4-qp",
    title: "Vocabulary question paper — test 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-4-ws",
    title: "Vocabulary worksheet — test 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-5-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 5",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-5-qp",
    title: "Vocabulary question paper — test 5",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-5-ws",
    title: "Vocabulary worksheet — test 5",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-6-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 6",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-6-qp",
    title: "Vocabulary question paper — test 6",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-6-ws",
    title: "Vocabulary worksheet — test 6",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-7-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 7",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-7-qp",
    title: "Vocabulary question paper — test 7",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-7-ws",
    title: "Vocabulary worksheet — test 7",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-8-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 8",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-8-qp",
    title: "Vocabulary question paper — test 8",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-8-ws",
    title: "Vocabulary worksheet — test 8",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-9-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 9",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-9-qp",
    title: "Vocabulary question paper — test 9",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-9-ws",
    title: "Vocabulary worksheet — test 9",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocabulary-bank-2",
    title: "Vocabulary bank — set 2",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocabulary-bank-2.pdf",
    description: "Additional vocabulary prompts for breadth and precision.",
  },
  {
    id: "worksheet-writing-vocab-ms-marking-scheme",
    title: "Writing vocabulary — marking scheme",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-vocab-ms-marking-scheme.pdf",
    description: "Marking scheme for the writing vocabulary question paper.",
  },
  {
    id: "worksheet-writing-vocab-qp",
    title: "Writing vocabulary — question paper",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-vocab-qp.pdf",
    description: "Writing-focused vocabulary questions for Paper 1 preparation.",
  },
  {
    id: "worksheet-writing-words-day-15",
    title: "Writing words — day 15",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-words-day-15.pdf",
    description: "Day-style vocabulary push for consistent writing improvement.",
  },
  // ── Quick Worksheets — MCQs ──────────────────────────────────────────
  {
    id: "mcq-punctuation-5min",
    title: "5-Minute Drill: Punctuation",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Punctuation",
    year: "Practice",
    fileUrl: "",
    description:
      "10 questions · 5 minutes. Dialogue format, em dashes, colons, and comma rules — the marks most students leave on the table.",
  },
  {
    id: "mcq-feelings-practice",
    title: "Feelings Practice Worksheet",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Reading",
    year: "Practice",
    fileUrl: "",
    description:
      "20 questions · 10 minutes. Read the quote and the context, then choose the feeling that best fits — exam-style vocabulary, no vague words.",
  },
  {
    id: "mcq-result-adjectives",
    title: "Result Adjectives Practice Worksheet",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Reading",
    year: "Practice",
    fileUrl: "",
    description:
      "20 questions · 10 minutes. Read the quote, picture the scene, and choose the adjective cluster that best describes it — using the 8-cluster framework.",
  },
  {
    id: "mcq-rewording-workshop",
    title: "Rewording Workshop: Pick the Best Rewording",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "",
    description:
      "15 questions · 8 minutes. Cambridge marking scheme points — pick the rewording that is precise, clear, and captures the full meaning without lifting, vagueness, or added content.",
  },
  {
    id: "mcq-short-response-q3b",
    title: "Short Response Practice Quiz — Q3(b)",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Practice",
    fileUrl: "",
    description:
      "10 questions · 5 minutes. Five real-world scenarios — identify whether the speaker agrees or disagrees, then pick the development that best supports their stated reason.",
  },
  {
    id: "impressions-practice-quiz",
    title: "Impressions Practice Quiz",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "",
    description:
      "12 questions · 10 minutes. Tone, impression words, inference, and precise meaning for Paper 1 Question 2.",
  },
  {
    id: "writers-effect-practice-quiz",
    title: "Writer's Effect Practice Quiz",
    category: "quick-worksheets",
    type: "mcq",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "",
    description:
      "12 questions · 10 minutes. Word class, meaning in context, and reader effect — Paper 1 Question 2 (writer's effect).",
  },
];

const curatedGeneralNotes: Resource[] = [
  {
    id: "directed-writing-complete-formats",
    title: "Directed Writing — Complete Formats",
    category: "general-notes",
    subCategory: "directed-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/olevel-directed-writing-all-formats-notes.pdf",
    description: "Complete article, report, speech, email, and letter formats for directed writing.",
  },
  {
    id: "directed-writing-pde-structure",
    title: "Directed Writing — PDE Structure",
    category: "general-notes",
    subCategory: "directed-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/pde-format.pdf",
    description: "Core Point–Development–Evaluation structure for high-control directed responses.",
  },
  {
    id: "directed-writing-notes-concepts",
    title: "Directed Writing — Notes & Concepts",
    category: "general-notes",
    subCategory: "directed-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/directed-writing-notes.pdf",
    description: "Development and evaluation logic for stronger ideas, flaws, and expansion.",
  },
  {
    id: "paper-2-marathon",
    title: "Paper 2 Marathon",
    category: "general-notes",
    subCategory: "directed-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Current",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/paper-2-marathon.pdf",
    description: "Complete walkthrough for Paper 2 writing mastery — Miss Jay's marathon guide.",
  },
  {
    id: "essay-writing-narrative",
    title: "Essay Writing — Narrative",
    category: "general-notes",
    subCategory: "essay-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/narrative-essay.pdf",
    description: "Narrative planning, conflict, climax, and resolution support for Paper 1 essays.",
  },
  {
    id: "essay-writing-descriptive",
    title: "Essay Writing — Descriptive",
    category: "general-notes",
    subCategory: "essay-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/descriptive-essay.pdf",
    description: "Descriptive writing guidance for controlled imagery, detail, and atmosphere.",
  },
  {
    id: "essay-writing-vocabulary-bank",
    title: "Essay Writing — Vocabulary Bank",
    category: "general-notes",
    subCategory: "essay-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/final-vocabulary-for-essay-writing.pdf",
    description: "Vocabulary bank with dialogue words, tone shifts, and expressive verbs for essays.",
  },
  {
    id: "essay-writing-sample-essays",
    title: "Essay Writing — Sample Essays",
    category: "general-notes",
    subCategory: "essay-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/sample-essay-writing.pdf",
    description: "Model essay samples showing structure, development, and exam-ready control.",
  },
  {
    id: "summary-writing-part-a",
    title: "Summary Writing — Part A",
    category: "general-notes",
    subCategory: "summary-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/summary-writing-part-a.pdf",
    description: "Core summary extraction method: skim, underline, and collect the best 12 points.",
  },
  {
    id: "summary-writing-part-b-short-response",
    title: "Summary Writing — Part B Short Response",
    category: "general-notes",
    subCategory: "summary-writing",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/part-b-short-response.pdf",
    description: "Opinion plus three developed details for the Paper 2 short-response rubric.",
  },
  {
    id: "grammar-complete-guide",
    title: "Grammar — Complete Guide",
    category: "general-notes",
    subCategory: "grammar",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/grammar-complete-guide.pdf",
    description: "Single source of truth for grammar, punctuation, sentence control, and writing-quality scoring.",
  },
  {
    id: "comprehension-question-1-core",
    title: "Comprehension — Question 1",
    category: "general-notes",
    subCategory: "comprehension",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/comprehension-question-1.pdf",
    description: "Core notes for understanding explicit and implicit meaning in Question 1.",
  },
  {
    id: "comprehension-use-of-language-core",
    title: "Comprehension — Use of Language",
    category: "general-notes",
    subCategory: "comprehension",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/comprehension-question-2-use-of-language.pdf",
    description: "Vocabulary choice and reader-effect notes for Use of Language work in Paper 2.",
  },
  {
    id: "comprehension-vocabulary-bank",
    title: "Comprehension — Vocabulary Bank",
    category: "general-notes",
    subCategory: "comprehension",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Core",
    fileUrl: "https://upyxhhbpdjlnbpraykow.supabase.co/storage/v1/object/public/resources/notes/vocabulary-for-comprehension.pdf",
    description: "Feelings, synonym scales, and precision vocabulary support for comprehension tasks.",
  },
];

const curatedResourceLibrary = [
  ...resourceLibrary.filter(
    (resource) =>
      resource.category !== "general-notes" &&
      resource.category !== "topicals" &&
      resource.category !== "checklists"
  ),
  ...curatedGeneralNotes,
  ...supplementalHubResources,
];

export const staticResources = finalizeResourcesForSite(curatedResourceLibrary);
const MISSING_PUBLIC_RESOURCE_URLS = new Set<string>([
  "/resources/changes-in-the-syllabus-1123.pdf",
  "/resources/complete-vocabulary-list-1123.pdf",
  "/resources/notes/common-grammatical-errors-worksheet.pdf",
  "/resources/notes/grammar-3.pdf",
  "/resources/notes/pde-explained.pdf",
  "/resources/notes/punctuation-worksheet-3.pdf",
  "/resources/notes/sentence-structures-worksheet.pdf",
  "/resources/o-level-1123-syllabus.pdf",
  "/resources/olevel-directed-writing-formats-1123-notes.pdf",
  "/resources/olevel-directed-writing-text-wise-evaluation-notes.pdf",
  "/resources/syllabus-1123-specification.pdf",
  "/resources/vocabulary-companion-1123.pdf",
  "/resources/worksheet-26-march-vocab-test-ms-marking-scheme.pdf",
  "/resources/worksheet-exam-hack-4.pdf",
  "/resources/worksheet-exam-hack-writers-effect.pdf",
  "/resources/worksheet-interviewer-question-practice.pdf",
  "/resources/worksheet-phrases-to-utilize.pdf",
  "/resources/worksheet-pop-quiz.pdf",
  "/resources/worksheet-sentences-you-can-use.pdf",
  "/resources/worksheet-tip-of-the-day-01.pdf",
  "/resources/worksheet-tip-of-the-day-02.pdf",
  "/resources/worksheet-tip-of-the-day-03.pdf",
  "/resources/worksheet-tip-of-the-day-04.pdf",
  "/resources/worksheet-tip-of-the-day-05.pdf",
  "/resources/worksheet-tip-of-the-day-06.pdf",
  "/resources/worksheet-vocab-test-1-qp.pdf",
  "/resources/worksheet-vocab-test-10-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-10-qp.pdf",
  "/resources/worksheet-vocab-test-10-ws.pdf",
  "/resources/worksheet-vocab-test-11-qp.pdf",
  "/resources/worksheet-vocab-test-11-ws.pdf",
  "/resources/worksheet-vocab-test-12-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-12-qp.pdf",
  "/resources/worksheet-vocab-test-12-ws.pdf",
  "/resources/worksheet-vocab-test-13-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-13-qp.pdf",
  "/resources/worksheet-vocab-test-13-ws.pdf",
  "/resources/worksheet-vocab-test-14-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-14-qp.pdf",
  "/resources/worksheet-vocab-test-14-ws.pdf",
  "/resources/worksheet-vocab-test-2-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-3-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-3-qp.pdf",
  "/resources/worksheet-vocab-test-4-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-4-qp.pdf",
  "/resources/worksheet-vocab-test-4-ws.pdf",
  "/resources/worksheet-vocab-test-5-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-5-qp.pdf",
  "/resources/worksheet-vocab-test-5-ws.pdf",
  "/resources/worksheet-vocab-test-6-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-6-qp.pdf",
  "/resources/worksheet-vocab-test-6-ws.pdf",
  "/resources/worksheet-vocab-test-7-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-7-qp.pdf",
  "/resources/worksheet-vocab-test-7-ws.pdf",
  "/resources/worksheet-vocab-test-8-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-8-qp.pdf",
  "/resources/worksheet-vocab-test-8-ws.pdf",
  "/resources/worksheet-vocab-test-9-ms-marking-scheme.pdf",
  "/resources/worksheet-vocab-test-9-qp.pdf",
  "/resources/worksheet-vocab-test-9-ws.pdf",
  "/resources/worksheet-vocabulary-bank-2.pdf",
  "/resources/worksheet-writing-vocab-ms-marking-scheme.pdf",
  "/resources/worksheet-writing-vocab-qp.pdf",
  "/resources/worksheet-writing-words-day-15.pdf",
]);

export const resources = staticResources.filter(
  (resource) => resource.type === "mcq" || !MISSING_PUBLIC_RESOURCE_URLS.has(resource.fileUrl)
);

export const siteConfig = {
  name: "Jaweria Amer",
  /** Short personal brand line (nav, footer, hero kicker, profile). */
  brandSubtitle: "Miss Jaweria, Your go-to English instructor",
  title: "Jaweria Amer — Miss Jaweria, Your go-to English instructor",
  description:
    "Rubric-driven Cambridge O Level English tutoring in Karachi. Structured practice, precise feedback, and mentorship that builds independent thinkers.",
  tagline: "Master CAIE English with Clarity and Care",
  stats: [
    { value: "3+", label: "Years Teaching Experience" },
    { value: "80%", label: "Students scored A+/A" },
    { value: "6", label: "CAIE Exam Sessions" },
  ],
  roadmap: [
    {
      step: 1,
      title: "Diagnostic Review",
      description: "We assess your current level, identify patterns, and pinpoint exactly what needs attention.",
    },
    {
      step: 2,
      title: "Structured Plan",
      description: "A clear, week-by-week plan aligned to your exam timeline and personal goals.",
    },
    {
      step: 3,
      title: "Targeted Practice",
      description: "Rubric-driven exercises, timed papers, and focused skill-building sessions.",
    },
    {
      step: 4,
      title: "Feedback & Refinement",
      description: "Detailed, examiner-style feedback on every piece of work. We fix what matters most.",
    },
    {
      step: 5,
      title: "Exam Readiness",
      description: "Full mock papers under real conditions. You walk into the exam hall prepared and confident.",
    },
  ],
  navigation: [
    { label: "Home", href: "/" },
    { label: "Courses", href: "/courses" },
    { label: "Resources", href: "/resources" },
    { label: "About", href: "/about" },
  ],
};
