import type { Resource } from "./data";

/**
 * Curated Topicals (Paper 1) and Scripts (1123) — static supplements merged in `data.ts`.
 * File paths under `public/resources/`; titles cleaned in `finalizeResourcesForSite` / `formatDisplayTitle`.
 *
 * Ingest: `node scripts/ingest-jaweria-vault.mjs` (logs each topical file as Added to stderr).
 * Not registered here (near-duplicate of existing public PDFs, left on disk): s25-paper-2-48-50-1.pdf,
 * s25-paper-2-49-50-1.pdf, s25-paper-2-49-50-2.pdf.
 */
export const supplementalHubResources: Resource[] = [
  {
    id: "topical-p1-3d51a75bae9c",
    title: "Copy of English Assessment 1- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/english-assessment-1-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-37c36388ee91",
    title: "Copy of PC 1- Pieces Of Silver- MS_",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-1-pieces-of-silver-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-dbf756136995",
    title: "Copy of PC 10- Whispering Meadow - MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-10-whispering-meadow-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-25bdaf04be37",
    title: "Copy of PC 2- The Lost Lagoon- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-2-the-lost-lagoon-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-23721be922bc",
    title: "Copy of PC 3- Road From Coorain- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-3-road-from-coorain-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-ec88afb9918c",
    title: "Copy of PC 4- Silver Boomerang- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-4-silver-boomerang-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-b87b640a4556",
    title: "Copy of PC 5- House In the Mist- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-5-house-in-the-mist-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-7abe0f8428c4",
    title: "Copy of PC 6-Nuclear landscape- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-6-nuclear-landscape-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-4b7622c3052f",
    title: "Copy of PC 7- Barrow Airport- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-7-barrow-airport-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-91df3fd6c21d",
    title: "Copy of PC 8-The Poisonous Snake- MS",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/ms/pc-8-the-poisonous-snake-ms.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-010f650ad3c0",
    title: "Practice Comprehension - 5- pdf",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-5-pdf.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-1c6d654a3c3f",
    title: "Practice Comprehension- 1-",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-1.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-ddb95e0f0ab0",
    title: "Practice Comprehension- 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-4.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-97c34975bc20",
    title: "Practice Comprehension- 9 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-9.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-ec1e8d1f03c3",
    title: "Practice Comprehension-10 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-10.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-b9957ead615e",
    title: "Practice Comprehension-2 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-2.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-61981eb134b8",
    title: "Practice Comprehension-3 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-3.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-d2e88458bc56",
    title: "Practice Comprehension-6 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-6.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-d2e1a664fddb",
    title: "Practice Comprehension-7 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-7.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-cdccefb37561",
    title: "Practice Comprehension-8 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Comprehension",
    fileUrl: "/resources/topicals/paper-1/comprehension/qp/practice-comprehension-8.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-77d1ed705d90",
    title: "Copy of Summary 1-  (Train) Solution",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-1-train-solution.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-ebb82c5fd68a",
    title: "Copy of Summary 10 (Aurora)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-10-aurora-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-ad3a8c997d8a",
    title: "Copy of Summary 3- Heavy Traffic",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-3-heavy-traffic.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-32e1eae33afa",
    title: "Copy of Summary 4 (Mobile Phones)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-4-mobile-phones-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-e728a910adfd",
    title: "Copy of Summary 5 (Sharks)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-5-sharks-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-889cf517a922",
    title: "Copy of Summary 6 (uniforms)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-6-uniforms-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-e430641a2dcb",
    title: "Copy of Summary 7 (Dam)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-7-dam-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-74be73f2d603",
    title: "Copy of Summary 8 (Tourism)- Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-8-tourism-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-9d80a395984b",
    title: "Copy of Summary 9 (Berlin School)-  Solved",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/ms/summary-9-berlin-school-solved.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-6991a2574b63",
    title: "Practice Summary - 1 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-1.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-71120afbe783",
    title: "Practice Summary - 10",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-10.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-64837fae5f75",
    title: "Practice Summary - 2 ",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-2.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-870459b224d9",
    title: "Practice Summary - 3",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-3.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-484f97795c6a",
    title: "Practice Summary - 4",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-4.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-88c6584066d1",
    title: "Practice Summary - 5",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-5.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-b9797e2540c4",
    title: "Practice Summary - 6",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-6.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-79ec88e00b1a",
    title: "Practice Summary - 7",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-7.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-7ec85413c405",
    title: "Practice Summary - 8",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-8.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "topical-p1-fea77881c3b8",
    title: "Practice Summary - 9",
    category: "topicals",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    section: "Summary",
    fileUrl: "/resources/topicals/paper-1/summary/qp/practice-summary-9.pdf",
    description: "Curated Paper 1 topical pack — vetted from the class materials set.",
  },
  {
    id: "script-s25-paper-1-47-50",
    title: "S25 Paper 1 (47/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-1-47-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-s25-paper-1-48-50",
    title: "S25 Paper 1 (48/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-1-48-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-s25-paper-2-46-50",
    title: "S25 Paper 2 (46/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-2-46-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-s25-paper-2-48-50",
    title: "S25 Paper 2 (48/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-2-48-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-s25-paper-2-49-50",
    title: "S25 Paper 2 (49/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-2-49-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-s25-paper-2-50-50",
    title: "S25 Paper 2 (50/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/s25-paper-2-50-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-w25-paper-2-45-50",
    title: "W25 Paper 2 (45/50)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "W25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/w25-paper-2-45-50.pdf",
    description: "Scored student script for review and practice.",
  },
  {
    id: "script-copy-of-1123-s24-er",
    title: "S24 1123 Principal Examiner Report",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "S24",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/copy-of-1123-s24-er.pdf",
    description: "Official principal examiner report (1123).",
  },
  {
    id: "script-copy-of-1123-s25-er",
    title: "S25 1123 Principal Examiner Report",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "S25",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/copy-of-1123-s25-er.pdf",
    description: "Official principal examiner report (1123).",
  },
  {
    id: "script-copy-of-1123-w24-er",
    title: "W24 1123 Principal Examiner Report",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "W24",
    section: "Scripts",
    fileUrl: "/resources/examiner-reports/copy-of-1123-w24-er.pdf",
    description: "Official principal examiner report (1123).",
  },
];
