/**
 * Ingest comprehension PDFs from `scripts/source/comprehension/` into
 * `public/resources/notes/` as `general-notes` + `subCategory: "comprehension"`.
 *
 * Usage (from `jaweria-amer/`):
 *   npx tsx scripts/ingest-comprehension-notes.ts
 */

import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

import type { Resource } from "../src/lib/data";
import { resources as existingResources } from "../src/lib/data";
import { supplementalHubResources as priorSupplements } from "../src/lib/resource-supplements";
import {
  findFirstDuplicate,
  humanizeResourceTitleFromFilename,
  slugifyFileStem,
} from "../src/lib/resource-ingestion";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const SOURCE_DIR = join(PROJECT_ROOT, "scripts", "source", "comprehension");
const NOTES_DIR = join(PROJECT_ROOT, "public", "resources", "notes");

function walkPdfFiles(dir: string, acc: string[] = []): string[] {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walkPdfFiles(p, acc);
    else if (st.isFile() && extname(name).toLowerCase() === ".pdf") acc.push(p);
  }
  return acc;
}

function uniqueDestSlug(originalBase: string, destDir: string): string {
  let stem = slugifyFileStem(originalBase.replace(/\.pdf$/i, ""));
  if (!stem) stem = "resource";
  let candidate = stem;
  let n = 0;
  while (existsSync(join(destDir, `${candidate}.pdf`))) {
    n += 1;
    candidate = `${stem}-${n}`;
  }
  return candidate;
}

/** Polish humanized titles for comprehension packs (display layer also uses formatDisplayTitle). */
function comprehensionNoteTitle(originalBase: string): string {
  let t = humanizeResourceTitleFromFilename(originalBase);
  t = t.replace(/^Comprehension\s+Question\s+/i, "Comprehension — Question ");
  t = t.replace(/^Vocabulary\s+For\s+Comprehension$/i, "Vocabulary for Comprehension");
  t = t.replace(/\(Use Of Language\)/i, "(Use of Language)");
  return t;
}

function main() {
  let skipped = 0;
  const collected: Resource[] = [];
  const pool: Resource[] = [...existingResources];

  mkdirSync(NOTES_DIR, { recursive: true });

  const files = walkPdfFiles(SOURCE_DIR);
  for (const abs of files) {
    const origBase = basename(abs);
    const slug = uniqueDestSlug(origBase, NOTES_DIR);
    const fileUrl = `/resources/notes/${slug}.pdf`;

    const title = comprehensionNoteTitle(origBase);
    const candidate: Resource = {
      id: slug,
      title,
      category: "general-notes",
      subCategory: "comprehension",
      subject: "English Language 1123",
      level: "O Level",
      paper: "Paper 2",
      year: "Practice",
      fileUrl,
      description: "Comprehension notes and practice aligned to Paper 2 reading.",
    };

    const dup = findFirstDuplicate(candidate, pool);
    if (dup) {
      skipped += 1;
      console.warn(`Duplicate skipped: ${origBase}`);
      continue;
    }

    copyFileSync(abs, join(NOTES_DIR, `${slug}.pdf`));
    pool.push(candidate);
    collected.push(candidate);
  }

  const merged = [...priorSupplements, ...collected];

  const outPath = join(PROJECT_ROOT, "src", "lib", "resource-supplements.ts");
  const body = `import type { Resource } from "./data";

/** Auto-generated by scripts/ingest-comprehension-notes.ts — ${collected.length} comprehension note(s), ${skipped} duplicate(s) skipped; ${merged.length} total supplemental resources. */
export const supplementalHubResources: Resource[] = ${JSON.stringify(merged, null, 2)};
`;
  writeFileSync(outPath, body, "utf8");
  console.log(
    `Ingested ${collected.length} comprehension resource(s); duplicates skipped: ${skipped}; ${merged.length} total supplements.`
  );
}

main();
