/**
 * Full replace of hub category `examiner-reports` (Scripts) from `scripts/source/scripts/` only.
 * Strips prior Scripts from supplements, clears `public/resources/examiner-reports/`, ingests fresh PDFs.
 *
 * Usage (run from `jaweria-amer/` so `process.cwd()` is the app root):
 *   npx tsx scripts/replace-scripts-resources.ts
 */

import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import type { Resource } from "../src/lib/data";
import { resources as existingResources } from "../src/lib/data";
import { supplementalHubResources as priorSupplements } from "../src/lib/resource-supplements";
import {
  findFirstDuplicate,
  hubCategoryForDiskFolder,
  inferResourceFieldsFromFilename,
  slugifyFileStem,
} from "../src/lib/resource-ingestion";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const PUBLIC_RESOURCES = join(PROJECT_ROOT, "public", "resources");
const EXAMINER_REPORTS_DIR = join(PUBLIC_RESOURCES, "examiner-reports");
/** PDFs to ingest — project-relative to cwd (expect `jaweria-amer/` when using npm/tsx from this app). */
const SCRIPTS_SOURCE_FOLDER = join(process.cwd(), "scripts", "source", "scripts");

function walkPdfFiles(dir: string, acc: string[] = []): string[] {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walkPdfFiles(p, acc);
    else if (st.isFile() && extname(name).toLowerCase() === ".pdf") acc.push(p);
  }
  return acc;
}

function uniqueDestSlug(originalBase: string, destDir: string): string {
  let stem = slugifyFileStem(originalBase.replace(/\.pdf$/i, ""));
  if (!stem) stem = "resource";
  let candidate = stem;
  let n = 0;
  while (existsSync(join(destDir, `${candidate}.pdf`))) {
    n += 1;
    candidate = `${stem}-${n}`;
  }
  return candidate;
}

function clearExaminerReportsDir() {
  if (!existsSync(EXAMINER_REPORTS_DIR)) {
    mkdirSync(EXAMINER_REPORTS_DIR, { recursive: true });
    return;
  }
  for (const name of readdirSync(EXAMINER_REPORTS_DIR)) {
    const p = join(EXAMINER_REPORTS_DIR, name);
    const st = statSync(p);
    if (st.isFile()) rmSync(p);
  }
}

function main() {
  const priorNonScripts = priorSupplements.filter((r) => r.category !== "examiner-reports");
  const pool: Resource[] = existingResources.filter((r) => r.category !== "examiner-reports");

  clearExaminerReportsDir();

  const diskFolder = "examiner-reports" as const;
  const hubCategory = hubCategoryForDiskFolder(diskFolder);
  const collected: Resource[] = [];
  let skipped = 0;

  const files = walkPdfFiles(SCRIPTS_SOURCE_FOLDER);
  for (const abs of files) {
    const origBase = basename(abs);
    const slug = uniqueDestSlug(origBase, EXAMINER_REPORTS_DIR);
    const fileUrl = `/resources/${diskFolder}/${slug}.pdf`;

    const fields = inferResourceFieldsFromFilename(origBase, hubCategory);
    const rel = relative(PROJECT_ROOT, abs);
    const paper =
      /paper\s*1|\/paper 1\/|p1\b|directed/i.test(rel + origBase)
        ? "Paper 1"
        : /paper\s*2|\/paper 2\/|p2\b|comprehension|summary/i.test(rel + origBase)
          ? "Paper 2"
          : fields.paper;

    const candidate: Resource = {
      id: slug,
      title: fields.title,
      category: hubCategory,
      subject: "English Language 1123",
      level: "O Level",
      paper,
      year: fields.year,
      fileUrl,
      description: fields.description,
    };

    const dup = findFirstDuplicate(candidate, pool);
    if (dup) {
      skipped += 1;
      console.warn(`Duplicate skipped: ${origBase}`);
      continue;
    }

    copyFileSync(abs, join(EXAMINER_REPORTS_DIR, `${slug}.pdf`));
    pool.push(candidate);
    collected.push(candidate);
  }

  const merged = [...priorNonScripts, ...collected];

  const outPath = join(PROJECT_ROOT, "src", "lib", "resource-supplements.ts");
  const body = `import type { Resource } from "./data";

/** Auto-generated by scripts/replace-scripts-resources.ts — ${collected.length} Scripts PDF(s), ${skipped} duplicate(s) skipped; ${merged.length} total supplemental resources. */
export const supplementalHubResources: Resource[] = ${JSON.stringify(merged, null, 2)};
`;
  writeFileSync(outPath, body, "utf8");
  console.log(
    `Scripts replaced: ${collected.length} new resource(s), ${skipped} skipped; ${merged.length} total supplements (non-Scripts + Scripts).`
  );
}

main();
